a=input("enter the name for a")
b=input("enter the name for b")
c=input("enter the name for c")
d=input("enter the name for d")
e=input("enter the rollno for e")
f=input("enter the rollno for f")
g=input("enter the rollno for g")
h=input("enter the rollno for h")
i=input("enter the age for i")
j=input("enter the age for j")
k=input("enter the age for k")
l=input("enter the age for l")
m=input("enter the dep for m")
n=input("enter the dep for n")
o=input("enter the dep for o")
p=input("enter the dep for p")
q=input("enter the email for q")
r=input("enter the email for r")
s=input("enter the email for s")
t=input("enter the email for t")
print("---------------------------------------------------------------------------------------------------")
print("|----|-------------|------|--------|------|-----|------|------------|------|----------------|-----|")
print("|----|    Name     |------| RollNo |------| Age |------| Department |------|    Email       |-----|")
print("|----|-------------|------|--------|------|-----|------|------------|------|----------------|-----|")
print("|----|    ",a,"   |------|", e  ,"  |------|",i ," |------|",   m   ,"       |------|",    q     ,"|-----|")
print("|----|-------------|------|--------|------|-----|------|------------|------|----------------|-----|")
print("|----|    ",b,"    |------|", f  ,"  |------|",j ," |------|",   n   ,"       |------|",    r     ,"|-----|")
print("|----|-------------|------|--------|------|-----|------|------------|------|----------------|-----|")
print("|----|    ",c,"  |------|", g  ,"  |------|",k ," |------|",   o   ,"       |------|",    s     ,"|-----|")
print("|----|-------------|------|--------|------|-----|------|------------|------|----------------|-----|")
print("|----|  ",d,"  |------|", h  ,"  |------|",l ," |------|",   p   ,"        |------|",    t     ,"|-----|")
print("|----|-------------|------|--------|------|-----|------|------------|------|----------------|-----|")
print("---------------------------------------------------------------------------------------------------")